/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_quiz_app.q;

import java.awt.Color;

/**
 *
 * @author MD Design
 */
public class Score extends javax.swing.JFrame {
Quiz_Form qitem  = new Quiz_Form();
Written_Answers witem = new Written_Answers();
float score = qitem.correct + witem.correct ;
    /**
     * Creates new form Score
     */
    public Score() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_FinalScore = new javax.swing.JPanel();
        Lbl_FinalScore = new javax.swing.JLabel();
        jPanel_ScoreNum = new javax.swing.JPanel();
        jLabel_ScoreNum = new javax.swing.JLabel();
        jLabel_Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_FinalScore.setBackground(new java.awt.Color(204, 204, 255));

        Lbl_FinalScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_FinalScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_FinalScore.setText("Final Score");

        javax.swing.GroupLayout jPanel_FinalScoreLayout = new javax.swing.GroupLayout(jPanel_FinalScore);
        jPanel_FinalScore.setLayout(jPanel_FinalScoreLayout);
        jPanel_FinalScoreLayout.setHorizontalGroup(
            jPanel_FinalScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinalScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_FinalScore, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_FinalScoreLayout.setVerticalGroup(
            jPanel_FinalScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FinalScoreLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(Lbl_FinalScore)
                .addGap(41, 41, 41))
        );

        jPanel_ScoreNum.setBackground(new java.awt.Color(102, 255, 255));
        jPanel_ScoreNum.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel_ScoreNumComponentAdded(evt);
            }
        });

        jLabel_ScoreNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Score.setText("jLabel1");

        javax.swing.GroupLayout jPanel_ScoreNumLayout = new javax.swing.GroupLayout(jPanel_ScoreNum);
        jPanel_ScoreNum.setLayout(jPanel_ScoreNumLayout);
        jPanel_ScoreNumLayout.setHorizontalGroup(
            jPanel_ScoreNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ScoreNumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ScoreNum, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_ScoreNumLayout.setVerticalGroup(
            jPanel_ScoreNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ScoreNumLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel_ScoreNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Score)
                    .addComponent(jLabel_ScoreNum))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_FinalScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_ScoreNum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel_FinalScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel_ScoreNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_ScoreNumComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel_ScoreNumComponentAdded
if(score >= 5){
    System.out.println(score);
    this.setBackground(Color.green);// TODO add your handling code here:
}
else { this.setBackground(Color.red);
System.out.println(score);
}
    }//GEN-LAST:event_jPanel_ScoreNumComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Score().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_FinalScore;
    private javax.swing.JLabel jLabel_Score;
    private javax.swing.JLabel jLabel_ScoreNum;
    private javax.swing.JPanel jPanel_FinalScore;
    private javax.swing.JPanel jPanel_ScoreNum;
    // End of variables declaration//GEN-END:variables
}
